#include "lightsensor_period.h"

void ls_period_init()
{
    LS_PERIOD_SIGNAL_TIMER->CR1 = TIM_CR1_URS;
    LS_PERIOD_SIGNAL_TIMER->CR2 = TIM_CR2_MMS_1;
    LS_PERIOD_SIGNAL_TIMER->SR = 0;
    LS_PERIOD_SIGNAL_TIMER->PSC = 23;
    LS_PERIOD_SIGNAL_TIMER->DIER = 0;
    LS_PERIOD_SIGNAL_TIMER->CCMR1 = TIM_CCMR1_CC1S_0 | TIM_CCMR1_CC2S_1;
    LS_PERIOD_SIGNAL_TIMER->CCMR2 = 0;
    LS_PERIOD_SIGNAL_TIMER->CCER = TIM_CCER_CC2P;
    LS_PERIOD_SIGNAL_TIMER->SMCR = 0
        | TIM_SMCR_MSM
        | TIM_SMCR_TS_0 | TIM_SMCR_TS_2
        | TIM_SMCR_SMS_2;
    LS_PERIOD_SIGNAL_TIMER->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E;

    LS_PERIOD_PIN_CR = (LS_PERIOD_PIN_CR & ~LS_PERIOD_PIN_CONFIG_MASK)
        | LS_PERIOD_PIN_CONFIG(CNF, 0);
}

void ls_period_enable()
{
    LS_PERIOD_SIGNAL_TIMER->CR1 |= TIM_CR1_CEN;
}

void ls_period_disable()
{
    LS_PERIOD_SIGNAL_TIMER->CR1 &= ~TIM_CR1_CEN;
}
